"""init

Revision ID: 872658d8d140
Revises: 
Create Date: 2024-10-09 23:14:03.954632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872658d8d140'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grades', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grades', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grades', 'grade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subjects', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grades', 'grade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grades', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grades', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
